### ISSUE TITLE
Set Jellyfin's user image through LDAP attribute

### ISSUE THREAD

**Issue by lewislarsen** [jellyfin/jellyfin-plugin-ldapauth#130] opened 2022-11-13 01:12 UTC
When configuring the plugin it would be amazing if we could specify the avatar attribute (typically jpegPhoto) for Jellyfin to populate from the LDAP server.

I quite enjoy seeing the avatar pulled from one central location, and this would be an awesome little addition.

Thanks for all your work. :)

**Comment by crobibero** [comment] 2022-11-13 01:22
Duplicate of https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/85

**Closed by crobibero** 2022-11-13 01:22 UTC
