### ISSUE TITLE
ldapexception: sizelimit exceeded (4) sizelimit exceeded

### ISSUE THREAD

**Issue by andynhoo** [jellyfin/jellyfin-plugin-ldapauth#35] opened 2020-05-20 00:54 UTC
I have all of this working on my Test system which does not have the number of users as the production system. When I try on the production system I get a LDAP size limit exceeded error in the logs. Using the ldapsearch command line query works just fine. Is there some setting to make the Ldap plugin handle a large number of users?

**Comment by andynhoo** [comment] 2020-07-03 18:32
LDAP not working up 1.000 users

When you have more than a thousand users the error is displayed and it is not possible to login with any ldap user

ERROR:
[15:29:41] [ERR] [25] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://localhost/Users/authenticatebyname
LdapException: Sizelimit Exceeded (4) Sizelimit Exceeded

System (please complete the following information):

OS: Linux Ubuntu
Virtualization:Docker
Clients: All
Jellyfin Version: 10.5.5
Installed Plugins: LDAP v6
Reverse Proxy: nginx

**Comment by oddstr13** [comment] 2020-07-30 11:25
Closing as duplicate of #39

**Closed by oddstr13** 2020-07-30 11:25 UTC
