### ISSUE TITLE
Password reset doesn't work with Active Directory

### ISSUE THREAD

**Issue by DemonAngeX2** [jellyfin/jellyfin-plugin-ldapauth#165] opened 2024-07-16 17:09 UTC
I can't change the users password with active directory.
the password attribute for AD is not the same as others LDAP. It's unicodePwd and need to be encoded.

Can you add the possibility to reset passwords with Active Directory please ? 
Thank you :)

**Comment by crobibero** [comment] 2024-07-16 17:14
Duplicate of the issue you created yesterday?
https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/164

**Closed by crobibero** 2024-07-16 17:14 UTC
